version: "3.9"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - tripswift-network
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    networks:
      - tripswift-network
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    volumes:
      - ./data/kafka:/var/run/docker.sock
    # logging:
    #   driver: none
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
    networks:
      - tripswift-network
    # logging:
    #   driver: none
  payment:
    container_name: "tripswift-payment"
    build:
      context: .
      dockerfile: ./server/payment/Dockerfile
    restart: always
    ports:
      - 8010:8010
    environment:
      PORT: 8010
      MONGO_URI: mongodb://mongo:27017/paymentDB
      NODE_ENV: development
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_AUTH_TOPIC: auth
      RAZORPAY_KEY_ID: rzp_test_mBBfOCZrMx5wNc
      RAZORPAY_KEY_SECRET: VUMKbAtOs9T2fy8WHlQmXj5l
    depends_on:
      - kafka
      - mongo
    networks:
      - tripswift-network
    volumes:
      - ./server/payment:/app/
      - /app/node_modules
  authentication:
    container_name: "tripswift-auth"
    build:
      context: .
      dockerfile: ./server/authentication/Dockerfile
    restart: always
    ports:
      - 8020:8020
    environment:
      - PORT=8020
      - MONGO_URI=mongodb://mongo:27017/authDB
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - JWT_SECRET_KEY_DEV=712fe68a80519cd3812dca082ec4ff2fd0dd2fe80d1f1c0d00871b387109767c39bb595df2a20a5dd6f54f60fbf096f5b23599f4584c8cdc85d9918ca9228504
      - JWT_EXPIRES_IN_DEV=15d
      - NODE_ENV=development
      - JWT_EXPIRES_IN=7d
      - JWT_SECRET_KEY=32ed647ffbc55050ecfe5b1b9a33600776973f441e9257fd73315c8444ac8eb1f1a813190f4c34c59caaa1304f5d09149fb2320d20195ac6645adb09f59ba59d
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_AUTH_TOPIC=auth
    depends_on:
      - kafka
      - mongo
    networks:
      - tripswift-network
    volumes:
      - ./server/authentication:/app/
      - /app/node_modules
  search:
    container_name: "tripswift-search-engine"
    build:
      context: ./server/search-engine
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8030:8030
    environment:
      - PORT=8030
      - MONGO_URI=mongodb+srv://techquotus:techquotus@cluster0.yjw0a6g.mongodb.net/?retryWrites=true&w=majority
      - ELASTICSEARCH_ID=98793fd777f24ad18b7ccefefe21796c:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvOjQ0MyRiZTkyOGFjOGI1ZTc0ZDk3YTY3MzM2OTFmMjkzNzMyZSQ4ZmM3M2E1N2VkNjM0N2U3YjAwMjY4YzcyOTNlNzA3Ng==
      - NODE_ENV=development
      - ELASTICSEARCH_USER=dwitidibyajyoti
      - ELASTICSEARCH_PASS=FJkggVbSMH8SFWG
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_AUTH_TOPIC=auth
    depends_on:
      - kafka
      - mongo
    networks:
      - tripswift-network
    volumes:
      - ./server/search-engine:/app/
      - /app/node_modules
  pms_api:
    container_name: "tripswift-pms_api"
    build:
      context: .
      dockerfile: ./server/pms_api/Dockerfile
    restart: always
    ports:
      - 8040:8040
    environment:
      - PORT=8040
      - MONGO_URI=mongodb://mongo:27017/propertyDB
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - JWT_SECRET_KEY_DEV=712fe68a80519cd3812dca082ec4ff2fd0dd2fe80d1f1c0d00871b387109767c39bb595df2a20a5dd6f54f60fbf096f5b23599f4584c8cdc85d9918ca9228504
      - JWT_EXPIRES_IN_DEV=15d
      - NODE_ENV=development
      - JWT_EXPIRES_IN=7d
      - JWT_SECRET_KEY=32ed647ffbc55050ecfe5b1b9a33600776973f441e9257fd73315c8444ac8eb1f1a813190f4c34c59caaa1304f5d09149fb2320d20195ac6645adb09f59ba59d
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_AUTH_TOPIC=auth
    depends_on:
      - kafka
      - mongo
    networks:
      - tripswift-network
    volumes:
      - ./server/pms_api:/app/
      - /app/node_modules
  user:
    container_name: "tripswift-user"
    build:
      context: .
      dockerfile: ./server/user/Dockerfile
    restart: always
    ports:
      - 8050:8050
    environment:
      - PORT=8050
      - MONGO_URI=mongodb://mongo:27017/user_db
      - NODE_ENV=development
      - JWT_EXPIRES_IN=7d
      - JWT_SECRET_KEY=32ed647ffbc55050ecfe5b1b9a33600776973f441e9257fd73315c8444ac8eb1f1a813190f4c34c59caaa1304f5d09149fb2320d20195ac6645adb09f59ba59d
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_AUTH_TOPIC=auth
    depends_on:
      - kafka
      - mongo
    networks:
      - tripswift-network
    volumes:
      - ./server/user:/app/
      - /app/node_modules
  # pms_client:
  #   container_name: "tripswift-pms_client"
  #   build:
  #     context: .
  #     dockerfile: ./client/pms-client/Dockerfile
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - kafka
  #     - mongo
  #     - search
  #     - authentication
  #     - payment
  #   networks:
  #     - tripswift-network
  #   volumes:
  #     - ./client/pms-client:/app/
  #     - /app/node_modules

  booking_engine:
    container_name: "tripswift-booking_engine"
    build:
      context: .
      dockerfile: ./server/booking_engine/Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/authDB
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - JWT_SECRET_KEY_DEV=712fe68a80519cd3812dca082ec4ff2fd0dd2fe80d1f1c0d00871b387109767c39bb595df2a20a5dd6f54f60fbf096f5b23599f4584c8cdc85d9918ca9228504
      - JWT_EXPIRES_IN_DEV=15d
      - NODE_ENV=development
      - JWT_EXPIRES_IN=7d
      - JWT_SECRET_KEY=32ed647ffbc55050ecfe5b1b9a33600776973f441e9257fd73315c8444ac8eb1f1a813190f4c34c59caaa1304f5d09149fb2320d20195ac6645adb09f59ba59d
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_AUTH_TOPIC=auth
    depends_on:
      - kafka
      - mongo
    networks:
      - tripswift-network
    volumes:
      - ./server/booking_engine:/app/
      - /app/node_modules

  booking_engine_client:
    container_name: "tripswift-booking_engine_client"
    build:
      context: .
      dockerfile: ./client/booking_engine_client/Dockerfile
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - kafka
      - mongo
      - search
      - authentication
      - payment
      - pms_api
    networks:
      - tripswift-network
    volumes:
      - ./client/booking_engine_client:/app/
      - /app/node_modules

networks:
  tripswift-network:

volumes:
  data:
